apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb # Required for StatefulSets
  replicas: 1 # Start with 1, scale up as needed
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # Security Context (Important!)
      securityContext:
        runAsUser: 1000 # Non-root user
        runAsGroup: 1000 # Non-root group
        fsGroup: 1000   # Necessary for volume permissions
      containers:
      - name: mongodb
        image: mongo:6.0 # Specify a version! "latest" is risky.
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi" # Slightly increased request
        livenessProbe: # Robust liveness probe
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15 # Adjust as needed
          periodSeconds: 10
        readinessProbe: # Robust readiness probe
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      # Pod Anti-Affinity (Highly Recommended)
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: mongodb
              topologyKey: kubernetes.io/hostname # Or failure-domain.beta.kubernetes.io/zone for multi-AZ
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard" # Or your preferred storage class