name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test Backend
      run: |
        cd backend
        mvn test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Test Frontend
      run: |
        cd frontend
        npm ci
        npm test

  build:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Convert repository name to lowercase
      run: |
        echo "REGISTRY=${REPO_NAME,,}" >>${GITHUB_ENV}
      env:
        REPO_NAME: 'ghcr.io/${{ github.repository_owner }}'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Backend
      run: |
        cd backend
        mvn clean package

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ env.REGISTRY }}/kyosk-backend:${{ env.IMAGE_TAG }}

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ env.REGISTRY }}/kyosk-frontend:${{ env.IMAGE_TAG }}

    - name: Update Kubernetes Manifests
      run: |
        cd k8s
        sed -i "s|image: ghcr.io/.*/kyosk-backend:.*|image: ghcr.io/${REGISTRY#ghcr.io/}/kyosk-backend:$IMAGE_TAG|" deployment.yaml
        sed -i "s|image: ghcr.io/.*/kyosk-frontend:.*|image: ghcr.io/${REGISTRY#ghcr.io/}/kyosk-frontend:$IMAGE_TAG|" deployment.yaml

    - name: Set up Git configuration
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit changes to Kubernetes manifests
      run: |
        cd k8s
        git add deployment.yaml
        git commit -m "Update Docker image tags in Kubernetes manifests"
        git push 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
